baseURL = "https://cneill/github.io/core-infra"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Core Infra"
theme = ["hugo-theme-gallery"]
enableEmoji = true

[params]
    defaultTheme = "dark"
    description = "Core infrastructure is cool and you should support it!"
    title = "Core Infra"
    [params.author]
        name = "Charles Neill"
    [params.socialIcons]
        github = "https://github.com/cneill/core-infra"
    [outputs]
        home = ["HTML", "RSS"]
        page = ["HTML"]
        section = ["HTML"]
