baseURL = "https://cneill/github.io/core-infra"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Core Infra"
theme = ["hugo-theme-gallery"]
enableEmoji = true

[[params.socialIcons]]
github = "https://github.com/cneill/core-infra"
