on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-inprogress: false

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      download_url: ${{ steps.get-hugo-release.outputs.download_url }}
      version: ${{ steps.get-hugo-release.outputs.version }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Grab latest Hugo release
        id: get-hugo-release
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./hugo-release.js');
            script({github, core});

      - name: Download Hugo release
        if: success()
        run: |
          curl -L ${{ steps.get-hugo-release.outputs.download_url }} -o hugo.tar.gz
          tar -xvf hugo.tar.gz
          sudo mv hugo /usr/local/bin/
          hugo version

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Hugo
        run: |
          hugo --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/" \
            --config hugo.toml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
