on:
  push:
    tags:
      - '*'

jobs:
  hugo:
    runs-on: ubuntu-latest
    outputs:
      download_url: ${{ steps.get-hugo-release.outputs.download_url }}
      version: ${{ steps.get-hugo-release.outputs.version }}
    steps:
      - name: Grab latest Hugo release
        id: get-hugo-release
        uses: actions/github-script@v7
        with:
          script: |
            const release = await github.rest.repos.getLatestRelease({
              "gohugoio",
              "hugo"
            });

            const version = response.data.tag_name;

            const asset = response.data.assets.find(asset =>
              asset.name.includes("extended") &&
              asset.name.includes("Linux-64bit") &&
              asset.name.endsWith(".tar.gz")
            );

            if (!asset) {
              throw new Error("No Hugo release binary found");
            }

            core.setOutput("download_url", asset.browser_download_url);
            core.setOutput("version", version);

            console.log(`Found Hugo ${version}`);
            console.log(`Download URL: ${asset.browser_download_url}`);

      - name: Download Hugo release
        if: success()
        run: |
          curl -L ${{ steps.get-release.outputs.download_url }} -o hugo.tar.gz
          tar -xvf hugo.tar.gz
          sudo mv hugo /usr/local/bin/
          hugo version
