on:
  push:
    tags:
      - '*'

jobs:
  hugo:
    runs-on: ubuntu-latest
    outputs:
      download_url: ${{ steps.get-hugo-release.outputs.download_url }}
      version: ${{ steps.get-hugo-release.outputs.version }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Grab latest Hugo release
        id: get-hugo-release
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./index.js');
            script({github, core});

      - name: Download Hugo release
        if: success()
        run: |
          curl -L ${{ steps.get-release.outputs.download_url }} -o hugo.tar.gz
          tar -xvf hugo.tar.gz
          sudo mv hugo /usr/local/bin/
          hugo version
