on:
  push:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      hugo_download_url: ${{ steps.get-hugo-release.outputs.hugo_download_url }}
      hugo_version: ${{ steps.get-hugo-release.outputs.hugo_version }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Grab latest Hugo release
        id: get-hugo-release
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('./hugo-get.js');
            script({github, core});

      - name: Cache Hugo
        id: cache-hugo
        uses: actions/cache@v4
        with:
          path: ~/.hugo/hugo
          key: hugo-${{ steps.get-hugo-release.outputs.hugo_version }}
          restore-keys: |
            hugo-

      - name: Download Hugo release
        if: steps.cache-hugo.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.hugo
          curl -L ${{ steps.get-hugo-release.outputs.hugo_download_url }} -o ~/.hugo/hugo.tar.gz
          cd ~/.hugo
          tar -xvf hugo.tar.gz
          sudo mv hugo /usr/local/bin/
          hugo version

      - name: Set Hugo path
        id: set-path
        run: |
          echo "Adding Hugo to PATH"
          echo "${HOME}/.hugo" >> $GITHUB_PATH

      - name: Install Dart Sass
        id: install-dart-sass
        run: sudo snap install dart-sass

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Hugo
        run: |
          hugo --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/" \
            --config hugo.toml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
